### ISSUE TITLE
ShoeGenerator

### ISSUE THREAD

**Issue by AbdurrahmanPhD** [fahadshamshad/prGAN#1]
Hi, when I try to run codes, I get an error like "ModuleNotFoundError: No module named 'ShoeGenerator' "

What is the ShoeGenerator ?

Thanks in advance

**Comment by fahadshamshad** [comment]
Hi, sorry for the late response. You can comment the line "import ShoeGenerator" as we have not provided the pretrained weights of the ShoeGenerator. We have provided pretrained weights of the CelebA generator only.
